# 
IF( WIN32 )
	SET( OPM_SYSTEM_NAME Windows )
	SET( OPM_C_COMPILER C:/MinGW/bin/gcc.exe )
	SET( OPM_CXX_COMPILER C:/MinGW/bin/g++.exe )
ELSE()
	SET( OPM_SYSTEM_NAME Generic )
ENDIF()


SET( CMAKE_SYSTEM_NAME ${OPM_SYSTEM_NAME} )

SET( CMAKE_C_COMPILER ${OPM_C_COMPILER} )
SET( CMAKE_CXX_COMPILER ${OPM_CXX_COMPILER} )

SET( CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER )
SET( CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY )
SET( CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY )
SET( CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY )