
# Set directories
SET( PS1080_SOURCE_DIR ${SOURCE_DIR}/Source/Drivers/PS1080 )
SET( PS1080_INCLUDE_DIR ${PS1080_SOURCE_DIR}/Include )

# Set compile and link flags
SET( PS1080_CXX_FLAGS "${EP_NONCMAKE_COMMON_CXX_FLAGS} -I${PS1080_INCLUDE_DIR} -I${PS1080_SOURCE_DIR} -I${LIBUSB_1_INCLUDE_DIR} -I${XNLIB_INCLUDE_DIR} -I${OPENNI2_LIB_INCLUDE_DIR} -I${INTERNAL_JPEG_INCLUDE_DIR} -I${DEPTHUTILS_INCLUDE_DIR}" )
SET( PS1080_LD_FLAGS "${CMAKE_EXE_LINKER_CXX_FLAGS} -L${LIBUSB_1_LIBRARY_DIR} -L${XNLIB_BIN_DIR} -L${OPENNI2_LIB_BIN_DIR}" )

# Add flags for Position Independent Code
IF( CMAKE_POSITION_INDEPENDENT_CODE )
	SET( PS1080_CXX_FLAGS "${PS1080_CXX_FLAGS} -fPIC" )
ENDIF()

# Create the build command arguments list
SET( PS1080_BUILD_ARGS CFLAGS=${PS1080_CXX_FLAGS} LDFLAGS=${PS1080_LD_FLAGS} ALLOW_WARNINGS=1 )

# If needed set debug information
IF( CMAKE_BUILD_TYPE MATCHES "Debug" )
	LIST( APPEND PS1080_BUILD_ARGS CFG=Debug )
ENDIF()

# Run the build command
EXECUTE_PROCESS( COMMAND make ${PS1080_BUILD_ARGS}
			WORKING_DIRECTORY ${PS1080_SOURCE_DIR} RESULT_VARIABLE build_result
)

IF( NOT "${build_result}" STREQUAL "0" )
	MESSAGE( STATUS "build PS1080 Failed!!!" )
	MESSAGE( FATAL_ERROR "build_result='${build_result}'" )
ENDIF()

RETURN( ${build_result} )
