# - Try to find OPENNI2
#
# IMPORTED Targets
# ^^^^^^^^^^^^^^^^
# This module defines :prop_tgt:`IMPORTED` target ``OPENNI2::OPENNI2``, if
# OPENNI2 has been found.
#
# Result Variables
# ^^^^^^^^^^^^^^^^
# This module defines the following variables:
#
#  OPENNI2_FOUND 			- system has OPENNI2
#  OPENNI2_INCLUDE_DIRS		- the OPENNI2 include directories
#  OPENNI2_LIBRARIES		- link these to use OPENNI2
#  OPENNI2_DEFINITIONS		- compiler flags for OPENNI2
#  OPENNI2_VERSION			- the version of OPENNI2 found (x.y.z)

IF( OPENNI2_FOUND )
	MESSAGE( STATUS "OPENNI2 is already in the cache." )
	return()
ENDIF()

INCLUDE( ${CMAKE_CURRENT_LIST_DIR}/LibFindMacros.cmake )
INCLUDE( ${CMAKE_ROOT}/Modules/SelectLibraryConfigurations.cmake )

# Dependencies
LIBFIND_PACKAGE( OPENNI2 XnLib )
LIBFIND_PACKAGE( OPENNI2 libusb-1.0 )

# Help CMake choose Static vs Shared Libraries
# Since CMake search order prefers Shared Libraries we only need
# to change the search order for Static Libraries
IF( NOT BUILD_SHARED_LIBS )
	IF( WIN32 )
		SET( CMAKE_FIND_LIBRARY_SUFFIXES .lib .a ${CMAKE_FIND_LIBRARY_SUFFIXES} )
	ELSE()
		SET( CMAKE_FIND_LIBRARY_SUFFIXES .a ${CMAKE_FIND_LIBRARY_SUFFIXES} )
	ENDIF()
ENDIF()

# Use pkg-config to get hints about paths if it exists
LIBFIND_PKG_CHECK_MODULES( OPENNI2_PKGCONF OPENNI2 )
SET( OPENNI2_DEFINITIONS ${OPENNI2_PKGCONF_CFLAGS_OTHER} )

# Include dir
FIND_PATH( OPENNI2_INCLUDE_DIR
  NAMES OpenNI.h
  HINTS ${OPENNI2_PKGCONF_INCLUDE_DIRS}
)

# The release library
FIND_LIBRARY( OPENNI2_LIBRARY_RELEASE
  NAMES OpenNI2
  HINTS ${OPENNI2_PKGCONF_LIBRARY_DIRS}
)

# The debug library
FIND_LIBRARY( OPENNI2_LIBRARY_DEBUG
  NAMES OpenNI2d
  HINTS ${OPENNI2_PKGCONF_LIBRARY_DIRS}
)

MARK_AS_ADVANCED( OPENNI2_LIBRARY_RELEASE OPENNI2_LIBRARY_DEBUG )

# This macro takes a library base name as an argument, and will choose good values
# for basename_LIBRARY, basename_LIBRARIES, basename_LIBRARY_DEBUG, and
# basename_LIBRARY_RELEASE depending on what has been found and set.
SELECT_LIBRARY_CONFIGURATIONS( OPENNI2 )

# Set by SELECT_LIBRARY_CONFIGURATIONS(), but we want the ones from LIBFIND_PROCESS() below.
UNSET( OPENNI2_FOUND )
UNSET( OPENNI2_LIBRARIES )

# The version number
IF( EXISTS "${OPENNI2_INCLUDE_DIR}/OniVersion.h" )
	SET( OPENNI2_H "${OPENNI2_INCLUDE_DIR}/OniVersion.h" )
ENDIF()

IF( OPENNI2_INCLUDE_DIR AND OPENNI2_H )
	FILE( STRINGS "${OPENNI2_H}" openni2_version_str
		REGEX "^#[\t ]*define[\t ]+ONI_VERSION_(MAJOR|MINOR|MAINTENANCE)[\t ]+[0-9]+$" )
	
	UNSET( OPENNI2_VERSION )
	FOREACH( VPART MAJOR MINOR MAINTENANCE )
		FOREACH( VLINE ${openni2_version_str} )
			IF( VLINE MATCHES "^#[\t ]*define[\t ]+ONI_VERSION_${VPART}[\t ]+([0-9]+)$" )
				SET( OPENNI2_VERSION_PART "${CMAKE_MATCH_1}" )
				IF( OPENNI2_VERSION )
					SET( OPENNI2_VERSION "${OPENNI2_VERSION}.${OPENNI2_VERSION_PART}" )
				ELSE()
					SET( OPENNI2_VERSION "${OPENNI2_VERSION_PART}" )
				ENDIF()
				UNSET( OPENNI2_VERSION_PART )
			ENDIF()
		ENDFOREACH()
	ENDFOREACH()
ENDIF()

# Set the include dir variables and the libraries and let libfind_process do the rest.
# NOTE: Singular variables for this library, plural for libraries this lib depends on.
SET( OPENNI2_PROCESS_INCLUDES ${OPENNI2_INCLUDE_DIR} ${XnLib_INCLUDE_DIRS} ${LIBUSB_1_INCLUDE_DIRS} )
SET( OPENNI2_PROCESS_LIBS ${OPENNI2_LIBRARY} ${XnLib_LIBRARIES} ${LIBUSB_1_LIBRARIES} )
LIBFIND_PROCESS( OPENNI2 )

# Set IMPORTED Targets
IF( OPENNI2_FOUND )
	IF( NOT TARGET OPENNI2::OPENNI2 )
		GET_FILENAME_COMPONENT( LIB_EXT ${OPENNI2_LIBRARY} EXT )
		IF( "${LIB_EXT}" MATCHES "a" OR "${LIB_EXT}" MATCHES "lib" )
			SET( LIB_TYPE STATIC )
		ELSE()
			SET( LIB_TYPE SHARED )
		ENDIF()
		
		ADD_LIBRARY( OPENNI2::OPENNI2 ${LIB_TYPE} IMPORTED )
		SET_TARGET_PROPERTIES( OPENNI2::OPENNI2 PROPERTIES
			INTERFACE_INCLUDE_DIRECTORIES "${OPENNI2_INCLUDE_DIRS}"
			VERSION "${OPENNI2_VERSION}" )

		IF( OPENNI2_LIBRARY_RELEASE )
			SET_PROPERTY( TARGET OPENNI2::OPENNI2 APPEND PROPERTY
				IMPORTED_CONFIGURATIONS RELEASE )
			SET_TARGET_PROPERTIES( OPENNI2::OPENNI2 PROPERTIES
				IMPORTED_LOCATION_RELEASE "${OPENNI2_LIBRARY_RELEASE}" )
		ENDIF()

		IF( OPENNI2_LIBRARY_DEBUG )
			SET_PROPERTY( TARGET OPENNI2::OPENNI2 APPEND PROPERTY
				IMPORTED_CONFIGURATIONS DEBUG )
			SET_TARGET_PROPERTIES( OPENNI2::OPENNI2 PROPERTIES
				IMPORTED_LOCATION_DEBUG "${OPENNI2_LIBRARY_DEBUG}" )
		ENDIF()

		IF( NOT OPENNI2_LIBRARY_RELEASE AND NOT OPENNI2_LIBRARY_DEBUG )
			SET_PROPERTY( TARGET OPENNI2::OPENNI2 APPEND PROPERTY
				IMPORTED_LOCATION "${OPENNI2_LIBRARY}" )
		ENDIF()
		
		IF( APPLE )
			SET( OPENNI2_DEFINITIONS "-DMACOS ${OPENNI2_DEFINITIONS}" )
		ELSEIF( UNIX )
			SET( OPENNI2_DEFINITIONS "-DUNIX -DGLX_GLXEXT_LEGACY ${OPENNI2_DEFINITIONS}" )
		ENDIF()
	ENDIF()
	
	MESSAGE( STATUS "  Include Dirs: ${OPENNI2_INCLUDE_DIRS}" )
	MESSAGE( STATUS "  Libraries: ${OPENNI2_LIBRARIES}" )
	IF( OPENNI2_DEFINITIONS )
		MESSAGE( STATUS "  Definitions: ${OPENNI2_DEFINITIONS}" )
	ENDIF()
ENDIF()
